//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryPostav
    {
        public int ID { get; set; }
        public Nullable<int> IDPostavshik { get; set; }
        public Nullable<int> IDMaterial { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual PartnerAndPostavchik PartnerAndPostavchik { get; set; }
    }
}
