//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.CreateProducts = new HashSet<CreateProduct>();
            this.HistoryPostavs = new HashSet<HistoryPostav>();
            this.ProductionProducts = new HashSet<ProductionProduct>();
            this.UpdateStorages = new HashSet<UpdateStorage>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> IDTypeMaterial { get; set; }
        public Nullable<int> IDPostavshik { get; set; }
        public Nullable<int> IDUnit { get; set; }
        public string Info { get; set; }
        public string Image { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> QunatityStorage { get; set; }
        public Nullable<int> MinQunatity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreateProduct> CreateProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryPostav> HistoryPostavs { get; set; }
        public virtual PartnerAndPostavchik PartnerAndPostavchik { get; set; }
        public virtual TypeMaterial TypeMaterial { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionProduct> ProductionProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UpdateStorage> UpdateStorages { get; set; }
    }
}
