//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProduct
    {
        public int ID { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> IDPartners { get; set; }
        public Nullable<int> QunatityProduct { get; set; }
        public Nullable<double> Summ { get; set; }
        public Nullable<System.DateTime> DateSale { get; set; }
        public Nullable<int> IDMestaSale { get; set; }
    
        public virtual MestaSale MestaSale { get; set; }
        public virtual PartnerAndPostavchik PartnerAndPostavchik { get; set; }
    }
}
