//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int ID { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<System.DateTime> DateEntry { get; set; }
        public Nullable<System.DateTime> DateExit { get; set; }
    
        public virtual User User { get; set; }
    }
}
