//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.ZakazProducts = new HashSet<ZakazProduct>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Summ { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> PredOpalata { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakazProduct> ZakazProducts { get; set; }
    }
}
