//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakazProduct
    {
        public int ID { get; set; }
        public Nullable<int> IDZakaz { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Summ { get; set; }
        public Nullable<int> partner_id { get; set; }
    
        public virtual PartnerAndPostavchik PartnerAndPostavchik { get; set; }
        public virtual Product Product { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
